name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: Hashnode Blog
        uses: varunsridharan/action-hashnode-blog@1.2

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: "susmitadey" # Hashnode Username
          COUNT: 3 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://susmitadey.vercel.app/blogs/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
